### ISSUE TITLE
Issue with list_products() and list_transactions()

### ISSUE THREAD

**Issue by ManishAradwad** [websideproject/paddle-billing-client#327]
## 🐛 Bug Report

Was getting `apiclient.exceptions.ClientError: 403 Error: Forbidden for url: https://sandbox-api.paddle.com/products` error when I did 

```
client = PaddleApiClient(authentication_method=HeaderAuthentication(token="my_client_token"))
client.list_products()
```

Then I changed the base_url:

```
client = PaddleApiClient(base_url="https://sandbox-vendors.paddle.com", authentication_method=HeaderAuthentication(token="my_client_token"))
```

Then i started getting this error:

```
Traceback (most recent call last):
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/apiclient/response_handlers.py", line 37, in get_request_data
    response_json = response.get_json()
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/apiclient/response.py", line 56, in get_json
    return self._response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py", line 81, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/paddle_billing_client/client.py", line 117, in list_products
    return self.get(
           ^^^^^^^^^
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/apiclient/client.py", line 129, in get
    return self.get_request_strategy().get(endpoint, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/apiclient/request_strategies.py", line 60, in get
    return self._make_request(self.get_session().get, endpoint, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/apiclient/request_strategies.py", line 103, in _make_request
    return self._decode_response_data(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/apiclient/request_strategies.py", line 136, in _decode_response_data
    return self.get_client().get_response_handler().get_request_data(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toji/Projects/minmax/.minmax/lib/python3.11/site-packages/apiclient/response_handlers.py", line 39, in get_request_data
    raise ResponseParseError(
apiclient.exceptions.ResponseParseError: Unable to decode response data to json. data='<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<link rel="icon" href="/favicon.ico" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="theme-color" content="#000000" />
<meta name="description" content="Paddle login" />
<meta name="robots" content="noindex, nofollow, noarchive, nosnippet, notranslate, noimageindex" />
<link rel="apple-touch-icon" href="/logo192.png" />

<link rel="manifest" href="/manifest.json" />
<script src="/config.js"></script>

<script async="false" src="/tag-config.js"></script>

<script async crossorigin="anonymous" src="https://www.googletagmanager.com/gtag/js?id=G-9XVE7HZLLZ"></script>


<script async crossorigin="anonymous" src="https://cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" defer></script>

<title>Paddle login</title>
<script type="module" crossorigin src="/assets/index-BcR4vATK.js"></script>
<link rel="stylesheet" crossorigin href="/assets/index-CbfY4aDy.css">
</head>
<body>
<noscript>You need to enable JavaScript to run this app.</noscript>
<div id="root"></div>
</body>
</html>
'
```

### Environment

* OS: macOS
* Python version, get it with: 3.11.7

```bash
python --version
```

**Comment by bgervan** [comment]
Hi, 

https://developer.paddle.com/api-reference/overview

The sandbox vendors url is for Paddle Classic, not for Paddle Billing.

Can you provide more info for the first error though? Did you use the right api key?

**Comment by bgervan** [comment]
Closing this as seems to be user error. You can reopen this with additional information
